employee/urls.py
from django.urls import path
from . import views

app_name = 'employee'

urlpatterns = [
    path('<int:pk>/',views.employee_details,name='employee_details')
]

mysite/urls.py
from django.contrib import admin
from django.urls import path,include
from . import views
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.home,name='home'),
    path('employee/',include('employee.urls',namespace='employee'))
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

employee/models.py
from django.db import models

# Create your models here.
class Employee(models.Model):
    first_name=models.CharField(max_length=100)
    last_name=models.CharField(max_length=100)
    photo=models.ImageField(upload_to='images')
    designation=models.CharField(max_length=100)
    email_adress=models.EmailField(max_length=100,unique=True)
    phone_number=models.CharField(max_length=12,blank=True)
    created_at=models.DateTimeField(auto_now_add=True)
    updated_at=models.DateTimeField(auto_now=True)



    def __str__(self):
        return self.first_name

employee/views.py
from django.shortcuts import get_object_or_404, render
from employee.models import Employee
from django.http import Http404, HttpResponse
# Create your views here.
def employee_details(request,pk):
    employee=get_object_or_404(Employee,pk=pk)
    context={
        'employee' :employee,
    }
    return render(request,'employee_details.html',context)

mysite/views.py
from django.http import HttpResponse
from django.shortcuts import render
from employee.models import Employee
def home(request):
    employee=Employee.objects.all()
    context={
        'employee':employee,
    }
    return render(request,'home.html',context)

templates/employee_details.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.8/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-sRIl4kxILFvY47J16cr9ZwB07vP4J8+LH7qKQnuqkuIAvNWLzeN8tE5YBujZqJLB" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.8/dist/js/bootstrap.bundle.min.js" integrity="sha384-FKyoEForCGlyvwx9Hj09JcYn3nv7wiPVlz7YYwJrWVcXK/BmnVDxM+D2scQbITxI" crossorigin="anonymous"></script>

    
</head>
<body>
    

<div class="container pt-5">
<div class="card mx-auto" style="width: 18rem;">
  <img class="card-img-top" src="{{ employee.photo.url }}" alt="Card image cap">
  <div class="card-body">
    <p class="card-text m-0"><strong>Name:</strong> {{ employee.first_name }} {{ employee.last_name }}</p>
    <p class="card-text m-0"><strong>Email:</strong> {{ employee.email_adress }}</p>
    <p class="card-text m-0"><strong>Designation:</strong> {{ employee.designation }}</p>
    <p class="card-text m-0"><strong>Phone:</strong> {{ employee.phone_number }}</p>
    <p class="card-text m-0"><strong>Created:</strong> {{ employee.created_at }}</p>
    <p class="card-text m-0"><strong>Updated:</strong> {{ employee.updated_at }}</p>
  </div>
  <a href="{% url 'home' %}" class="btn btn-primary">Back to home</a>
</div>

</div>


</body>
</html>

templates/home.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.8/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-sRIl4kxILFvY47J16cr9ZwB07vP4J8+LH7qKQnuqkuIAvNWLzeN8tE5YBujZqJLB" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.8/dist/js/bootstrap.bundle.min.js" integrity="sha384-FKyoEForCGlyvwx9Hj09JcYn3nv7wiPVlz7YYwJrWVcXK/BmnVDxM+D2scQbITxI" crossorigin="anonymous"></script>

    
</head>
<body>
    

    <div class="container pt-5">
            <h1>Eemployee List</h1>
        <table class="table">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">Full name</th>
      <th scope="col">Distiantion</th>
      <th scope="col">Phone no</th>
    </tr>
  </thead>
  <tbody>
    {% for emp in employee %}
    <tr>
      <th scope="row">{{forloop.counter}}</th>
      <td><a href="{% url 'employee:employee_details' emp.id %}">{{emp.first_name}} {{emp.last_name}}</a></td>
      <td>{{emp.designation}}</td>
      <td>{{emp.phone_number}}</td>
    </tr>
    {% endfor %}
  </tbody>
</table>
<img src="{% static 'images/Screenshot 2025-08-25 224815.png' %}" alt="" width="400">
</div>


</body>
</html>